### PR TITLE
Update for VS 2017 and VSIX schema 2.0

### PR DESCRIPTION
**Pull request by Shazwazza**
I've updated the project to work with VS 2017. I've changed the ID and name to AttachTo-2017 and updated a few things in the manifest. Not too many changes but it works. VS2017 RC seems to have an issue with debugging extensions but if you build this you can install the VSIX by double clicking on it in the /bin folder.

Let me know if you can get this published if you get a chance to test it, otherwise I'm happy to publish it.

### CODE REVIEW

**Comment by bugthesystem** [comment]
@Shazwazza Thanks 👍 I'll have look at to this asap (We can keep using`AttachTo-Next` name to prevent confusion for existing users who waiting for new version, what are your thoughts?)

**Comment by Shazwazza** [comment]
Hi, I know this has been a very long time now and I totally forgot to respond but can we post the latest build to AttachTo-Next on the marketplace for vs 2017 ?

**Comment by Shazwazza** [comment]
Hi again, just wanted to check to see if this can be pushed up to https://marketplace.visualstudio.com/items?itemName=ziyasal.AttachTo-Next ?

**Comment by Shazwazza** [comment]
There's also this fork too for vs2017 but they don't seem to have pushed anything to the marketplace either https://github.com/brunoamancio/AttachTo/tree/master/VSIX%20Files

**Pull request merged**
